// Code generated by docuconf. DO NOT EDIT.
package orders_api

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-api"
		generator: {
			language: "typescript"
			sdk:      "@docuconf/nestjs"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			items:       "string"
			encoding:    "csv"
			separator:   ","
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		MAINTENANCE_MODE: {
			type:        "bool"
			description: "Reject writes during maintenance windows"
			default:     false
		}
		PORT: {
			type:        "int"
			description: "Port the API listens on"
			min:         1
			max:         65535
			default:     3000
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Timeout for upstream requests"
			encoding:    "go"
			max:         "5m"
			default:     "30s"
		}
		WEBHOOK_KEYS: {
			type:          "list"
			description:   "Keys that verify the signature on incoming payment webhooks"
			details:       "A webhook is accepted when it is signed with any key in the list, so the key can be rotated without turning webhooks away. To rotate:\n\n 1. add the new key as the second item, and roll out;\n 2. switch the sender to the new key;\n 3. remove the old key, and roll out.\n\nEach key is 32 to 256 characters, so an empty or truncated key fails at boot. Without this variable, the service rejects every webhook."
			secret:        true
			items:         "string"
			encoding:      "csv"
			separator:     ","
			minItems:      1
			maxItems:      2
			itemMinLength: 32
			itemMaxLength: 256
		}
	}
	files: {
		settings: {
			type:        "config"
			format:      "json"
			description: "Business settings: currency and order limits"
			required:    true
			path:        "/etc/orders/config/settings.json"
			reload:      "watch"
			schema: {
				type: "object"
				properties: {
					currency: {
						enum: ["EUR", "USD", "GBP"]
					}
					maxItemsPerOrder: {
						type:    "integer"
						minimum: 1
					}
				}
				required: ["currency", "maxItemsPerOrder"]
				additionalProperties: false
			}
		}
		tls: {
			type:        "tls"
			description: "Certificate the API serves HTTPS with"
			secret:      true
			path:        "/etc/orders/tls"
			reload:      "watch"
			dnsNames: ["orders.internal"]
			minRemaining: "168h"
		}
	}
}
