import { describe, expect, it } from "vitest";
import {
  GENERIC,
  VarReport,
  closeSchema,
  formatDuration,
  intBounds,
  nonRe2Feature,
  parseDuration,
  precheckVar,
  renderContract,
  type VarBase,
} from "../src/index.ts";

const port: VarBase = { name: "PORT", type: "int", secret: false, required: false, contract: {} };

describe("precheckVar", () => {
  it("treats empty as unset except for strings, and checks number syntax", () => {
    expect(precheckVar(port, "", new VarReport(port))).toEqual({ value: undefined, ok: true });
    const report = new VarReport(port);
    expect(precheckVar(port, "0x50", report).ok).toBe(false);
    expect(report.violations[0]).toMatchObject({ code: "invalid_type", message: 'expected a base-10 integer (got "0x50")' });
  });

  it("redacts secret messages", () => {
    const decl: VarBase = { ...port, secret: true };
    const report = new VarReport(decl);
    precheckVar(decl, "12a", report);
    expect(report.violations[0]!.message).toBe(GENERIC.invalid_type);
  });
});

describe("shared helpers", () => {
  it("formats durations canonically", () => {
    expect(formatDuration(5_400_000)).toBe("1h30m");
    expect(parseDuration("1m30s")).toBe(90_000);
  });

  it("caps int bounds to safe integers", () => {
    const warnings: string[] = [];
    expect(intBounds("N", { exclusiveMin: 0 }, warnings)).toEqual({ min: 1, max: Number.MAX_SAFE_INTEGER });
    expect(intBounds("N", { max: 2 ** 60 }, warnings).max).toBe(Number.MAX_SAFE_INTEGER);
    expect(warnings).toEqual(["N: max capped at Number.MAX_SAFE_INTEGER"]);
  });

  it("finds non-RE2 features", () => {
    expect(nonRe2Feature("^(?=a)")).toBe("lookahead (?=...)");
    expect(nonRe2Feature("^[a-z]+$")).toBeUndefined();
  });

  it("closes object schemas and strips docuconf keywords", () => {
    expect(
      closeSchema({ $schema: "x", type: "object", properties: { a: { type: "string", pattern: "^\\/a", "x-docuconf": 1 } } }),
    ).toEqual({ type: "object", properties: { a: { type: "string", pattern: "^/a" } }, additionalProperties: false });
  });

  it("renders a contract with the generator it is given", () => {
    const out = renderContract(
      { name: "svc", appVersion: undefined, vars: new Map([["PORT", { contract: { type: "int", description: "Listen port" } }]]), fileContracts: new Map() },
      {},
      { language: "typescript", sdk: "@docuconf/test", version: "1.2.3" },
    );
    expect(out).toContain('sdk:      "@docuconf/test"');
    expect(out.startsWith("// Code generated by docuconf. DO NOT EDIT.\npackage svc\n")).toBe(true);
  });
});
