import { describe, expect, it } from "vitest";
import {
  GENERIC,
  VarReport,
  closeSchema,
  formatDuration,
  injectorScheme,
  intBounds,
  intItem,
  nonRe2Feature,
  parseDuration,
  precheckVar,
  renderContract,
  type VarBase,
} from "../src/index.ts";

const secretUrl: VarBase = { name: "DATABASE_URL", type: "url", secret: true, required: true, contract: {} };
const port: VarBase = { name: "PORT", type: "int", secret: false, required: false, contract: {} };

describe("injector references (SPEC §4.5.1)", () => {
  it("recognises vault:, op:// and ref+ and names only the scheme", () => {
    expect(injectorScheme("vault:secret/data/db#url")).toBe("vault:");
    expect(injectorScheme("op://vault/item/field")).toBe("op://");
    expect(injectorScheme("ref+vault://secret/db#/url")).toBe("ref+vault");
    expect(injectorScheme("ref+not a backend")).toBe("ref+");
    expect(injectorScheme("postgres://db/app")).toBeUndefined();
    expect(injectorScheme("Vault:x")).toBeUndefined();
  });

  it("fails a secret with invalid_type and a message without the value", () => {
    const report = new VarReport(secretUrl);
    const r = precheckVar(secretUrl, "vault:secret/data/hunter2#url", report);
    expect(r.ok).toBe(false);
    expect(report.violations).toEqual([
      {
        input: "DATABASE_URL",
        kind: "var",
        code: "invalid_type",
        message: "holds an unresolved vault: reference; the injector that should resolve it did not run",
      },
    ]);
  });

  it("leaves non-secrets alone", () => {
    const decl: VarBase = { ...secretUrl, secret: false, type: "string" };
    expect(precheckVar(decl, "vault:x", new VarReport(decl))).toEqual({ value: "vault:x", ok: true });
  });
});

describe("precheckVar", () => {
  it("treats empty as unset except for strings, and checks number syntax", () => {
    expect(precheckVar(port, "", new VarReport(port))).toEqual({ value: undefined, ok: true });
    const report = new VarReport(port);
    expect(precheckVar(port, "0x50", report).ok).toBe(false);
    expect(report.violations[0]).toMatchObject({ code: "invalid_type", message: 'expected a base-10 integer (got "0x50")' });
  });

  it("redacts secret messages", () => {
    const decl: VarBase = { ...port, secret: true };
    const report = new VarReport(decl);
    precheckVar(decl, "12a", report);
    expect(report.violations[0]!.message).toBe(GENERIC.invalid_type);
  });
});

describe("shared helpers", () => {
  it("formats durations canonically", () => {
    expect(formatDuration(5_400_000)).toBe("1h30m");
    expect(parseDuration("1m30s")).toBe(90_000);
  });

  it("caps int bounds to safe integers", () => {
    const warnings: string[] = [];
    expect(intBounds("N", { exclusiveMin: 0 }, warnings)).toEqual({ min: 1, max: Number.MAX_SAFE_INTEGER });
    expect(intBounds("N", { max: 2 ** 60 }, warnings).max).toBe(Number.MAX_SAFE_INTEGER);
    expect(warnings).toEqual(["N: max capped at Number.MAX_SAFE_INTEGER"]);
  });

  it("finds non-RE2 features", () => {
    expect(nonRe2Feature("^(?=a)")).toBe("lookahead (?=...)");
    expect(nonRe2Feature("^[a-z]+$")).toBeUndefined();
  });

  it("closes object schemas and strips docuconf keywords", () => {
    expect(
      closeSchema({ $schema: "x", type: "object", properties: { a: { type: "string", pattern: "^\\/a", "x-docuconf": 1 } } }),
    ).toEqual({ type: "object", properties: { a: { type: "string", pattern: "^/a" } }, additionalProperties: false });
  });

  it("renders a contract with the generator it is given", () => {
    const out = renderContract(
      { name: "svc", appVersion: undefined, vars: new Map([["PORT", { contract: { type: "int", description: "Listen port" } }]]), fileContracts: new Map() },
      {},
      { language: "typescript", sdk: "@docuconf/test", version: "1.2.3" },
    );
    expect(out).toContain('sdk:      "@docuconf/test"');
    expect(out.startsWith("// Code generated by docuconf. DO NOT EDIT.\npackage svc\n")).toBe(true);
  });
});

describe("int list items (SPEC §4.3 itemMin, itemMax)", () => {
  it("checks syntax, safe range and item bounds", () => {
    const b = { itemMin: 0, itemMax: 1023 };
    expect(intItem("7", b)).toEqual({ value: 7 });
    expect(intItem(7, b)).toEqual({ value: 7 });
    expect(intItem("x", b)).toMatchObject({ code: "invalid_type" });
    expect(intItem(" 7", b)).toMatchObject({ code: "invalid_type" });
    expect(intItem("1", b)).toEqual({ value: 1 });
    expect(intItem(1.5, b)).toMatchObject({ code: "invalid_type" });
    expect(intItem("7", {})).toEqual({ value: 7 });
    expect(intItem("-1", b)).toMatchObject({ code: "out_of_range" });
    expect(intItem("1024", b)).toMatchObject({ code: "out_of_range" });
    expect(intItem("9007199254740993", {})).toMatchObject({ code: "out_of_range" });
  });

  it("names itemMin and itemMax when capping them", () => {
    const warnings: string[] = [];
    expect(intBounds("IDS", { min: -1e300 }, warnings, { min: "itemMin", max: "itemMax" })).toEqual({
      min: -Number.MAX_SAFE_INTEGER,
      max: Number.MAX_SAFE_INTEGER,
    });
    expect(warnings).toEqual(["IDS: itemMin capped at -Number.MAX_SAFE_INTEGER"]);
  });
});
