import { cueFields, cueLabel } from "./cue.ts";

const DNS_LABEL = /^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$/;

export interface ContractOptions {
  /** Service name (a DNS label). Defaults to the declaration's name. */
  name?: string;
  /** Application version or git SHA (metadata.appVersion). */
  appVersion?: string;
  /** CUE package clause. Defaults to the service name with "-" replaced by "_". */
  packageName?: string;
}

/** What a contract is built from: any SDK's declaration has these. */
export interface ContractSource {
  name: string | undefined;
  appVersion: string | undefined;
  vars: ReadonlyMap<string, { contract: Record<string, unknown> }>;
  fileContracts: ReadonlyMap<string, Record<string, unknown>>;
}

/** metadata.generator: the SDK that wrote the contract. */
export interface Generator {
  language: string;
  sdk: string;
  version: string;
}

function byName(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** The contract as plain data, in output order (SPEC §4, §11.2 item 3). */
export function buildContract(decl: ContractSource, opts: ContractOptions, generator: Generator): Record<string, unknown> {
  const name = opts.name ?? decl.name;
  if (name === undefined) throw new Error("docuconf: no service name; pass a name option or --name");
  if (!DNS_LABEL.test(name)) throw new Error(`docuconf: service name "${name}" must be a DNS label (${DNS_LABEL.source})`);
  const appVersion = opts.appVersion ?? decl.appVersion;
  const metadata: Record<string, unknown> = { name };
  if (appVersion !== undefined) metadata["appVersion"] = appVersion;
  metadata["generator"] = { language: generator.language, sdk: generator.sdk, version: generator.version };

  const vars: Record<string, unknown> = {};
  for (const n of [...decl.vars.keys()].sort(byName)) vars[n] = decl.vars.get(n)!.contract;
  const contract: Record<string, unknown> = {
    apiVersion: "docuconf.dev/v1alpha1",
    kind: "ConfigContract",
    metadata,
    vars,
  };
  if (decl.fileContracts.size > 0) {
    const files: Record<string, unknown> = {};
    for (const n of [...decl.fileContracts.keys()].sort(byName)) files[n] = decl.fileContracts.get(n);
    contract["files"] = files;
  }
  return contract;
}

export function packageNameFor(service: string): string {
  const p = service.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z]/.test(p) ? p : `svc_${p}`;
}

/** Writes the contract as a CUE file that unifies with contract.#Contract. */
export function renderContract(decl: ContractSource, opts: ContractOptions, generator: Generator): string {
  const data = buildContract(decl, opts, generator);
  const meta = data["metadata"] as { name: string };
  const pkg = opts.packageName ?? packageNameFor(meta.name);
  if (cueLabel(pkg) !== pkg) throw new Error(`docuconf: "${pkg}" is not a valid CUE package name`);
  return [
    "// Code generated by docuconf. DO NOT EDIT.",
    `package ${pkg}`,
    "",
    'import "docuconf.dev/contract"',
    "",
    "contract.#Contract & {",
    cueFields(Object.entries(data), "\t"),
    "}",
    "",
  ].join("\n");
}
