/**
 * Markdown documentation for a contract (SPEC §11.2: SDKs SHOULD generate
 * docs from the declaration): one table of variables and one of file
 * inputs, in contract order.
 */
function cell(v: unknown): string {
  return String(v).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function code(v: unknown): string {
  const s = typeof v === "string" ? v : JSON.stringify(v);
  return `\`${s.replace(/`/g, "'")}\``;
}

function rules(c: Record<string, unknown>): string {
  const out: string[] = [];
  const num = (k: string) => (typeof c[k] === "number" && Math.abs(c[k] as number) < Number.MAX_SAFE_INTEGER ? (c[k] as number) : undefined);
  const lo = num("min") ?? (typeof c["min"] === "string" ? c["min"] : undefined);
  const hi = num("max") ?? (typeof c["max"] === "string" ? c["max"] : undefined);
  if (lo !== undefined && hi !== undefined) out.push(`${lo} to ${hi}`);
  else if (lo !== undefined) out.push(`at least ${lo}`);
  else if (hi !== undefined) out.push(`at most ${hi}`);
  if (c["minLength"] !== undefined) out.push(`at least ${c["minLength"]} characters`);
  if (c["maxLength"] !== undefined) out.push(`at most ${c["maxLength"]} characters`);
  if (c["pattern"] !== undefined) out.push(`matches ${code(c["pattern"])}`);
  if (Array.isArray(c["values"])) out.push(`one of ${(c["values"] as unknown[]).map(code).join(", ")}`);
  if (Array.isArray(c["schemes"])) out.push(`scheme ${(c["schemes"] as unknown[]).join(", ")}`);
  if (c["items"] !== undefined) out.push(`${c["items"]} items${c["separator"] !== undefined && c["separator"] !== "," ? ` separated by ${code(c["separator"])}` : ""}`);
  if (c["minItems"] !== undefined) out.push(`at least ${c["minItems"]} items`);
  if (c["maxItems"] !== undefined) out.push(`at most ${c["maxItems"]} items`);
  if (c["default"] !== undefined) out.push(`default ${code(c["default"])}`);
  if (c["deprecated"] !== undefined) out.push(`deprecated: ${(c["deprecated"] as { message: string }).message}`);
  return out.join("; ");
}

/** The contract (as buildContract returns it) as Markdown. */
export function renderMarkdown(contract: Record<string, unknown>): string {
  const meta = contract["metadata"] as { name: string; appVersion?: string };
  const vars = (contract["vars"] ?? {}) as Record<string, Record<string, unknown>>;
  const files = (contract["files"] ?? {}) as Record<string, Record<string, unknown>>;
  const lines = [`# ${meta.name} configuration`, "", "<!-- Code generated by docuconf. DO NOT EDIT. -->", ""];
  if (meta.appVersion !== undefined) lines.push(`Version: ${code(meta.appVersion)}`, "");
  lines.push("## Environment variables", "");
  if (Object.keys(vars).length === 0) lines.push("None.", "");
  else {
    lines.push("| Variable | Type | Required | Secret | Description | Rules |", "|---|---|---|---|---|---|");
    for (const [name, c] of Object.entries(vars)) {
      lines.push(`| ${code(name)} | ${cell(c["type"])} | ${c["required"] === true ? "yes" : "no"} | ${c["secret"] === true ? "yes" : "no"} | ${cell(c["description"] ?? "")} | ${cell(rules(c))} |`);
    }
    lines.push("");
  }
  if (Object.keys(files).length > 0) {
    lines.push("## Files", "", "| Input | Type | Path | Required | Description |", "|---|---|---|---|---|");
    for (const [name, f] of Object.entries(files)) {
      lines.push(`| ${code(name)} | ${cell(f["type"])} | ${code(f["path"])} | ${f["required"] === true ? "yes" : "no"} | ${cell(f["description"] ?? "")} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
