// Code generated by docuconf. DO NOT EDIT.
package orders_web

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-web"
		generator: {
			language: "typescript"
			sdk:      "@docuconf/t3"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type:        "url"
			description: "Postgres connection string for the orders database"
			required:    true
			secret:      true
			schemes: ["postgres"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Timeout for a single request"
			encoding:    "go"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		WEBHOOK_KEYS: {
			type:          "list"
			description:   "Keys that verify the signature on incoming payment webhooks"
			details:       "A webhook is accepted when it is signed with any key in the list, so the key can be rotated without turning webhooks away. To rotate:\n\n 1. add the new key as the second item, and roll out;\n 2. switch the sender to the new key;\n 3. remove the old key, and roll out.\n\nEach key is 32 to 256 characters, so an empty or truncated key fails at boot. Without this variable, the service rejects every webhook."
			secret:        true
			items:         "string"
			encoding:      "csv"
			separator:     ","
			minItems:      1
			maxItems:      2
			itemMinLength: 32
			itemMaxLength: 256
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Number of background order workers"
			min:         1
			max:         64
			default:     4
		}
	}
}
