// Code generated by docuconf. DO NOT EDIT.
package orders_api

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-api"
		generator: {
			language: "typescript"
			sdk:      "@docuconf/t3"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			items:       "string"
			encoding:    "csv"
			separator:   ","
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		MAINTENANCE_MODE: {
			type:        "bool"
			description: "Reject writes during maintenance windows"
			default:     false
		}
		PORT: {
			type:        "int"
			description: "Port the API listens on"
			min:         1
			max:         65535
			default:     8443
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Timeout for upstream requests"
			encoding:    "go"
			max:         "5m"
			default:     "30s"
		}
	}
	files: {
		settings: {
			type:        "config"
			format:      "json"
			description: "Business settings: currency and order limits"
			required:    true
			path:        "/etc/orders/config/settings.json"
			reload:      "watch"
			schema: {
				type: "object"
				properties: {
					currency: {
						type: "string"
						enum: ["EUR", "USD", "GBP"]
					}
					maxItemsPerOrder: {
						type:             "integer"
						exclusiveMinimum: 0
						maximum:          9007199254740991
					}
				}
				required: ["currency", "maxItemsPerOrder"]
				additionalProperties: false
			}
		}
		tls: {
			type:        "tls"
			description: "Certificate the API serves HTTPS with"
			secret:      true
			path:        "/etc/orders/tls"
			reload:      "watch"
			dnsNames: ["orders.internal"]
			minRemaining: "168h"
		}
	}
}
